/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TestLibraries;

import Login.LoginPanel;
import Login.Space;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.ImageIcon;
import static javax.swing.SwingConstants.CENTER;

/**
 *
 * @author Champe
 */
public class LoginExample extends javax.swing.JFrame {

    /**
     * Creates new form LoginExample
     */
    public LoginExample() {
        initComponents();
        setLoginWindow();
        setMainWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginExample.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginExample.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginExample.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginExample.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginExample().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

        private void setLoginWindow() {
        LoginPanel login = new LoginPanel();
        
        //Fondo de panel
        try{
            login.setBackgroundColor(new Color(56, 181, 165));
            login.setImageLogo(new ImageIcon(getClass().getResource("/Images/Logo.png")));
            login.setImgLogoPosition(new Space(100,46,600,400));
        }catch(NullPointerException npe){
            System.out.println("Error en imagen");
        }
        
        //Propiedades de labels
        login.setFontProperties("labels", new Font("Franklin Gothic Demi Cond", 0, 18), new Color(0, 0, 0));
        
        //Propiedades de buttons
        login.setFontProperties("buttons", new Font("Franklin Gothic Demi Cond", 0, 18), new Color(255, 255, 255));
        login.setComponentProperties("buttons", new Color(0, 0, 0), null, 0);
        
        //Propiedades de textfields
        login.setFontProperties("fields", new Font("Franklin Gothic Demi Cond", 0, 14), new Color(0, 0, 0));
        login.setComponentProperties("fields", new Color(255, 255, 255), null, 0);
        
        
        //Posicionamos los componentes
        login.placeComponents(login.lblUser, new Space(110, 350, -1, -1));
        login.placeComponents(login.lblPassword, new Space(346, 350, -1, -1));
        login.placeComponents(login.txtUser, new Space(110, 375, 200, 40));
        login.placeComponents(login.pswPassword, new Space(346, 375, 200, 40));
        login.placeComponents(login.btnLogin, new Space(583, 375, 110, 40));
        
        //Agregamos el panel de logueo
        this.add(login, CENTER);
    }

    private void setMainWindow() {
        this.setTitle("Nombre Aplicación - Tipo Aplicación ver. 1.0");
        this.setSize(new Dimension(800,600));
        //this.setResizable(false);
        this.setLocationRelativeTo(null);
    }
    
}
